# Generated by Django 2.2.1 on 2020-11-19 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('idAlert', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=25)),
                ('descrip', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
                ('falta', models.DateTimeField(default=django.utils.timezone.now)),
                ('ffin', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Informe001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('cemptitu', models.IntegerField()),
                ('segmento', models.CharField(max_length=50)),
                ('importe', models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
    ]
